Debug tunnel to k8s cluster
Signed-off-by: Samuel Bernardo <samuel@lip.pt>

diff --git a/scripts/deploy_wordpress b/scripts/deploy_wordpress
--- a/scripts/deploy_wordpress
+++ b/scripts/deploy_wordpress
@@ -1,14 +1,32 @@
 #!/usr/bin/env bash
 BASTION_NODE="194.210.120.36"
 MASTER_NODE="10.0.0.67"
+SOCKS_TUNNEL_PORT=38080
+K8S_API_PORT=6443
 #mkdir -p ~/.ssh
 #ssh-keyscan -H ${BASTION_NODE} > ~/.ssh/known_hosts
 #chmod 600 ~/.ssh/known_hosts
-#echo "#Debug SSH_KEYFILE: ${SSH_KEYFILE}"
-#echo "#Debug KUBECONFIG: ${KUBECONFIG}"
-ssh -qND 6443 -i ${SSH_KEYFILE} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ${SSH_KEYFILE} -W %h:%p ${SSH_USER}@${BASTION_NODE}" ${SSH_USER}@${MASTER_NODE} &
+#echo "Debug SSH_KEYFILE: ${SSH_KEYFILE}"
+#echo "Debug KUBECONFIG: ${KUBECONFIG}"
+ssh -qND ${SOCKS_TUNNEL_PORT} -i ${SSH_KEYFILE} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ${SSH_KEYFILE} -W %h:%p ${SSH_USER}@${BASTION_NODE}" ${SSH_USER}@${MASTER_NODE} &
+SSH_EXIT="$?"
 SSH_PID="$!"
-echo "Last command error code: $? | SSH_PID: ${SSH_PID}"
+if [[ "x${SSH_PID}" == "x" || "x${SSH_EXIT}" == "x" || ${SSH_EXIT} != 0 ]]; then
+    echo "ssh socks tunnel failed with error code: ${SSH_EXIT}"
+    exit 1;
+fi
+echo ""
+echo "Test access to the kubernetes API"
+echo ""
+https_proxy=socks5h://localhost:${SOCKS_TUNNEL_PORT} curl -k -v https://localhost:${K8S_API_PORT}/api
+K8S_API_EXIT="$?"
+if [[ "x${K8S_API_EXIT}" == "x" && ${K8S_API_EXIT} != 0 ]]; then
+    echo "curl to kubernetes api failed with error code: ${SSH_EXIT}"
+    exit 1;
+fi
+echo ""
+echo "Deploy kubernetes infrastructure"
+echo ""
 kubectl apply -k /examples
 if ! kubectl rollout status deployment wordpress --timeout 3600s; then
     echo "Someting went wrong!.. undo the current rollout and rollback to the previous revision."
