Debug ssh proxy
Signed-off-by: Samuel Bernardo <samuel@lip.pt>

diff --git a/scripts/deploy_wordpress b/scripts/deploy_wordpress
--- a/scripts/deploy_wordpress
+++ b/scripts/deploy_wordpress
@@ -8,6 +8,7 @@ MASTER_NODE="10.0.0.67"
 #echo "#Debug KUBECONFIG: ${KUBECONFIG}"
 ssh -qND 6443 -i ${SSH_KEYFILE} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -i ${SSH_KEYFILE} -W %h:%p ${SSH_USER}@${BASTION_NODE}" ${SSH_USER}@${MASTER_NODE} &
 SSH_PID="$!"
+echo "Last command error code: $? | SSH_PID: ${SSH_PID}"
 kubectl apply -k /examples
 if ! kubectl rollout status deployment wordpress --timeout 3600s; then
     echo "Someting went wrong!.. undo the current rollout and rollback to the previous revision."
